# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1beFxMa5svsQQ8dBbghm-d1nZhw3Qqzku
"""

n, m = map(int, input().split())
s = input()


def is_safe(i: int, j: int, s: str) -> bool:
    c = i
    r = j
    for k in s:
        if k == 'U':
            r -= 1
        elif k == 'D':
            r += 1
        elif k == 'L':
            c -= 1
        elif k == 'R':
            c += 1
        if r < 0 or r >= n or c < 0 or c >= m:
            return False
    return True


def check(n: int, m: int, s: str) -> bool:
    for i in range(m):
        for j in range(n):
            if is_safe(i, j, s):
                return True
    return False


print('Safe' if check(n, m, s) else 'Unsafe')